version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --port 27017
